lsmashinput: Use libavresample for resampling decoded audio data.
Now, (L-SMASH+)Libav reader can handle decoded audio data even if the decoder handles only IEEE floating point sample format.

diff --git a/AviUtl/configure b/AviUtl/configure
--- a/AviUtl/configure
+++ b/AviUtl/configure
@@ -81,9 +81,9 @@ libdir=""
 CFLAGS="-Wall -std=gnu99 -I. -I$SRCDIR"
 AU_LDFLAGS="-shared -Wl,--dll,--add-stdcall-alias"
 LDFLAGS="-L."
-DEPLIBS="liblsmash libavformat libavcodec libswscale libavutil"
+DEPLIBS="liblsmash libavformat libavcodec libswscale libavresample libavutil"
 
-SRC_INPUT="lsmashinput.c colorspace.c colorspace_simd.c libavsmash_input.c libav_input.c avs_input.c dummy_input.c progress_dlg.c"
+SRC_INPUT="lsmashinput.c colorspace.c colorspace_simd.c resample.c libavsmash_input.c libav_input.c avs_input.c dummy_input.c progress_dlg.c"
 SRC_MUXER="lsmashmuxer.c progress_dlg.c"
 SRC_DUMPER="lsmashdumper.c"
 
@@ -202,6 +202,12 @@ log_echo "checking for libswscale..."
 if ! cc_check "$CFLAGS" "$LDFLAGS $LIBS $XLIBS" "libswscale/swscale.h" "sws_getCachedContext(0,0,0,0,0,0,0,0,0,0,0);" ; then
     log_echo "error: libswscale checking failed."
     error_exit "libswscale/swscale.h might not be installed or some libs missing."
+fi
+
+log_echo "checking for libavresample..."
+if ! cc_check "$CFLAGS" "$LDFLAGS $LIBS $XLIBS" "libavresample/avresample.h" "avresample_open(0);" ; then
+    log_echo "error: libavresample checking failed."
+    error_exit "libavresample/avresample.h might not be installed or some libs missing."
 fi
 
 LDFLAGS="$AU_LDFLAGS $LDFLAGS"
